### ISSUE TITLE
[Software paper] Statement of need

### ISSUE THREAD

**Issue by aazocar** [bbye98/mdcraft#12]
This is part of JOSS review over at https://github.com/openjournals/joss-reviews/issues/7013

In the general, the statement of need focuses more on reasserting and describing the features and modules of MDCraft, which is already done in the Summary section. 

Furthermore, one of the main necessities described is to support on-the-fly analysis (Line 47); but there are no examples or further description of how MDCraft addresses this. Some sentences to clarify this point would be great.

**Comment by pw0908** [comment]
Addressing your comments:
1. While we do re-assert the features provided by mdcraft, we do highlight how these features fill gaps currently in the field. Firstly, in the case of OpenMM, we provide support throughout the simulation process, making it more accessible for novice users. Our analysis modules, in contrast to the ones existing in the field, provide more flexibility without requiring users to look at the low-level code. I suppose we could provide some context for the need for GCMe, image charge and slab corrections; however, this was the topic of @bbye98's other paper, running into the risk of plagiarism. As such, I can't think of much else to add to the statement of need that would remain MDCraft-specific.
2. Ill clarify this statement in the paper.
