### ISSUE TITLE
[Software paper] State of the field

### ISSUE THREAD

**Issue by aazocar** [bbye98/mdcraft#13]
This is part of JOSS review over at https://github.com/openjournals/joss-reviews/issues/7013

> Do the authors describe how this software compares to other commonly-used packages?

I have checked this point, but it could be further strengthened on the text. The comparison to MDAnalysis and MDTraj could be more detailed. Additionally, maybe you could take a look and see if these other packages are relevant: 
[freud](https://freud.readthedocs.io/en/latest/)
[pytraj](https://amber-md.github.io/pytraj/latest/analysis)
[pysimm](https://pysimm.org/)

**Comment by pw0908** [comment]
I'll add a few sentences on how MDcraft compares to MDAnalysis, MDTraj, freud and pytraj. Pysimm seems to no longer be supported?

**Comment by aazocar** [comment]
Thanks for changes, I'll mark this as completed from my side.
