### ISSUE TITLE
[Software paper] References

### ISSUE THREAD

**Issue by aazocar** [bbye98/mdcraft#14]
References are needed for the following:

(Line 29) static and dynamic structure factors, and auto-correlation functions for polymers

**Comment by pw0908** [comment]
These properties are very standard and their definitions aren't typically cited. In the case of the Onsager Transport coefficients, our implementation borrowed from the referenced article. I can add a reference to a standard textbook if that helps?

**Comment by aazocar** [comment]
I brought this up since the [`calculate_structure_factor`](https://mdcraft.readthedocs.io/en/latest/api/mdcraft.analysis.structure.calculate_structure_factor.html#mdcraft.analysis.structure.calculate_structure_factor) and [`correlation_fft`](https://mdcraft.readthedocs.io/en/latest/api/mdcraft.algorithm.correlation.correlation_fft.html#mdcraft.algorithm.correlation.correlation_fft) functions have references in the API docs. However, I would defer to you on whether these references need to be added on the paper.

**Comment by pw0908** [comment]
Oh, that's a good point. Those references refer to the algorithms we use to obtain those properties. We should have referenced them. Will fix this ASAP.
