### ISSUE TITLE
LAMMPSDUMPREADER missing `ts` input

### ISSUE THREAD

**Issue by ananyavenk** [bbye98/mdcraft#2]
[    def _read_next_timestep(self) -> ReaderBase._Timestep:](https://github.com/bbye98/mdcraft/blob/1afd8c8158e2074ac4bbce0504677cc6e45038a4/src/mdcraft/analysis/reader.py#L225)

Hi Ben,

Thanks for building MDCraft! I found a small issue with the LAMMPS dump reader where `_read_next_timestep` should be able to take in `ts` as an optional argument.

Thanks!

**Comment by pw0908** [comment]
Fixed with the above commit. We'll include it in the next release!
