### ISSUE TITLE
CI tests failing

### ISSUE THREAD

**Issue by srmnitc** [bbye98/mdcraft#3]
This is part of the JOSS review at https://github.com/openjournals/joss-reviews/issues/7013

Tests seem to be failing with `ModuleNotFoundError: No module named 'dynasor'`

**Comment by bbye98** [comment]
Turns out `dynasor==2.0.0` requires `importlib-metadata<5`, but the newest `sphinx==7.4.6` requires `importlib-metadata>=6`. Fixed this issue by forcing `dynasor>=2` in the `requirements.txt` and `environment.yml` files.
