### ISSUE TITLE
[Functionality/Example usage] Module LAMMPS

### ISSUE THREAD

**Issue by aazocar** [bbye98/mdcraft#6]
This is part of JOSS review over at https://github.com/openjournals/joss-reviews/issues/7013

It is stated on the paper (line 16) that the software extends the functionality of OpenMM and LAMMPS simulation packages, by introducing custom force fields, etc. This is not shown in any examples or usage guide specifically for LAMMPS. This is one of the core features mentioned in the paper and for a user to verify the functionality there should be an example.

**Comment by pw0908** [comment]
This is poor wording on our part. The features listed are only made available to OpenMM simulations. As for LAMMPS, only the analysis submodules are compatible with it. As such, any OpenMM examples we give will also be applicable to simulations run using LAMMPS. I'll re-word the paper accordingly.

The only LAMMPS-specific feature we provide is our own LAMMPSDUMP trajectory reader. This is currently being used in a rather recent project and, as it is such a niche feature, we didn't feel it appropriate to bring up in the main paper. I do think an example use of this specific reader should be given and will do so.

**Comment by aazocar** [comment]
Thanks for clarifying this. I'll go ahead and close the issue.
