### ISSUE TITLE
[Functionality/Example usage] Module OpenMM

### ISSUE THREAD

**Issue by aazocar** [bbye98/mdcraft#7]
This is part of JOSS review over at https://github.com/openjournals/joss-reviews/issues/7013

Regarding this module, there is good API documentation but potential new users of the software would benefit from having more extensive examples for the openMM system extensions and tools https://mdcraft.readthedocs.io/en/latest/api/mdcraft.openmm.system.html#module-mdcraft.openmm.system

Specifically, those mentioned in the paper: add_image_charges and add_slab_correction

Another related aspect, is the Gaussian core model with smeared electrostatics (GCMe) mentioned on the paper, but it is not clear where this can be found on the API docs.

**Comment by pw0908** [comment]
A few updates on this issue:
1. @bbye98 Has added an extensive example going over the GCMe forcefield within the [docs](https://mdcraft.readthedocs.io/en/latest/notebooks/user_guide/gcme_polyelectrolyte_edlc.html).
2. As mentioned in an earlier comment in the paper issue, there is an extensive set of examples given in [this repository](https://github.com/bbye98/gcme/tree/main) using mdcraft. This is something the other reviewer has mentioned and, although we are discussion the option of simply referring to this repository within mdcraft, we can move some of these examples over if you believe it is necessary.
