### ISSUE TITLE
[Performance] Performance claims of the software

### ISSUE THREAD

**Issue by aazocar** [bbye98/mdcraft#9]
This is part of JOSS review over at https://github.com/openjournals/joss-reviews/issues/7013

In the paper the following claims are mentioned, some clarification / data or additional references would be good.

* Line 18: "..,  introducing custom force fields, such as the **efficient** and intuitive ... GCMe"
* Line 24: "...  trajectories stored in **memory-efficient** formats."
* Line 50: "... **performance optimizations** that are not typically available in other simulation packages."

**Comment by pw0908** [comment]
The benchmarks of these implementations have been provided within @bbye98's [recent publication](https://doi.org/10.1021/acs.jctc.4c00603) Table 1. We can mention this manuscript within the repository. Additionally, the benchmark codes have also been provided in the [gcme repository](https://github.com/bbye98/gcme/tree/main/benchmark). As we may do with the examples, we could move these benchmarks into mdcraft. 

Would a simple reference to the published text be sufficient? Or would you prefer that we provide all the codes explicitly within the repository?

**Comment by aazocar** [comment]
I would say that adding the benchmark section in the README is sufficient to support the performance statements  in lines 18 and 50 with regards to GCMe and `openmm` module.  I would say there is no need to move the benchmarks to the mdcraft repository. 

One question would still be, what are the memory-efficient formats mentioned in line 24? Is this specifically for I/O? Would you say this is also addressed in the benchmark section?

**Comment by pw0908** [comment]
I think there may have been a misunderstanding at this line: we can read and write memory-efficient formats (such as netcdf), but this is just using already-established file formats which we didn't implement. As such, I don't think it's on us to justify this claim.
